### ISSUE TITLE
Not working with text + images

### ISSUE THREAD

**Issue by bellancaf** [tinacious/react-animated-show-more#6]
Hey there :) 

I wanted to try the pack and it was super cool and easy to implement. 
However, I ended up trying it on a text box that passes images as well and it does not work properly. 

Here two examples 
-> https://uat.feralhorses.co.uk/artworks/trident-seed *does not work* 
-> https://uat.feralhorses.co.uk/artworks/habemus-hominem *works* 

Do you have any idea why?

**Comment by tinacious** [comment]
Hi @bellancaf, I tried to load both your links and neither load due to the following error: 

![image](https://user-images.githubusercontent.com/1856992/87383019-3fb1ec00-c54d-11ea-803c-02022df1aff4.png)

I would recommend creating an isolated use case of the error you're experiencing on Codesandbox as it seems like those links point to a development environment that is constantly changing: https://codesandbox.io

What you describe, e.g. passing in a text box with images, I don't see why it wouldn't work. This was created to support any elements. Your custom toggle should implement render prop `isOpen`.

Will close for now. Please feel free to reopen once you can provide more details and a working reproduction. I would need more information before being able to help.

Thank you!
